# ------------------------- Repository Settings ------------------------------ #

site_name: Beacon Project Website
site_description: 'Website for the GA4GH biomedical Beacon project'
site_author: 'Michael Baudis, Ana Alonso Ayuso, Laureen Fromont & Beacon Developers'
copyright: '&copy; Copyright 2021-2026, Beacon Documentation Contributors'
repo_name: 'dev-beacon-web-ana.github.io'
repo_url: https://github.com/AnaT-DCO/dev-beacon-web-ana.github.io
edit_uri: edit/main/docs/
repo_icon: " [:fontawesome-brands-github:](https://github.com/ga4gh-beacon/ga4gh-beacon.github.io/tree/main/docs)"

# ------------------------ Navigation Menu ----------------------------------- #

nav:
    - Introduction: /
    - Beacon Features: Beacon-Features
    - Deployment Guide: Deployment-Guide
    - Resources: Resources
    - Team: Team
    - Newsletter: Newsletter
    - FAQs: FAQ
    - How to cite Beacon?: How-to-cite-Beacon

# ------------------- Mkdocs Configurattion and Extensions-------------------- #

extra_css: [css/theme_overrides.css]

plugins:
  - search
  - macros
  - mermaid2

markdown_extensions:
    - toc:
        toc_depth: 2-3
        permalink: true
    - admonition
    - attr_list
    - footnotes
    - md_in_html
    - pymdownx.critic
    - pymdownx.caret
    - pymdownx.details
    - pymdownx.keys
    - pymdownx.mark
    - pymdownx.tilde
    - pymdownx.saneheaders
    - pymdownx.superfences
    - pymdownx.magiclink:
        hide_protocol: true
    - pymdownx.tabbed:
        alternate_style: true
    - pymdownx.tasklist:
        custom_checkbox: true
    - tables
    - mdx_gh_links:
        user: ga4gh-beacon
        repo: ga4gh-beacon.github.io
    - pymdownx.emoji:
          emoji_index: !!python/name:materialx.emoji.twemoji
          emoji_generator: !!python/name:materialx.emoji.to_svg
          options:
            custom_icons:
              - extras/.icons
    - pymdownx.superfences:
        custom_fences:
            - name: mermaid
              class: mermaid
              format: !!python/name:mermaid2.fence_mermaid   

theme:
    custom_dir: extras
    name: material
    palette:
        primary: teal
    logo: img/GA-logo.png
    favicon: img/ga4gh_circle.ico
    icon:
        repo: fontawesome/brands/github-alt
        admonition:
          warning: lock
          security: lock
    features:
        - content.tabs.link
        - search.highlight
        - search.share
        - navigation.instant
        - navigation.tracking
        - navigation.sections

# Options
extra:
  excerpt_separator: <!--more-->
  blog_list_length: 100
  news:
    dir: news
  minutes:
    dir: minutes
  publications:
    dir: publications
  contacts:
    dir: people
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/ga4gh-beacon

# https://pypi.org/project/mkdocs-with-pdf/ for more PDF configuration ...
